// Offline MITRE ATT&CK helper: a compact enterprise cheat sheet + a keyword
// suggester so analysts who don't know technique IDs can pick the right one.
const tactics = [
  { id: "reconnaissance", name: "Reconnaissance" },
  { id: "resource-development", name: "Resource Development" },
  { id: "initial-access", name: "Initial Access" },
  { id: "execution", name: "Execution" },
  { id: "persistence", name: "Persistence" },
  { id: "privilege-escalation", name: "Privilege Escalation" },
  { id: "defense-evasion", name: "Defense Evasion" },
  { id: "credential-access", name: "Credential Access" },
  { id: "discovery", name: "Discovery" },
  { id: "lateral-movement", name: "Lateral Movement" },
  { id: "collection", name: "Collection" },
  { id: "command-and-control", name: "Command and Control" },
  { id: "exfiltration", name: "Exfiltration" },
  { id: "impact", name: "Impact" },
];
const T = (id, name, tactic, keywords) => ({ id, name, tactic, keywords });
const techniques = [
  T("T1595", "Active Scanning", "reconnaissance", ["scan", "nmap", "port scan", "recon", "probe"]),
  T("T1566", "Phishing", "initial-access", ["phish", "email", "attachment", "malicious link", "lure", "spearphish"]),
  T("T1566.001", "Spearphishing Attachment", "initial-access", ["attachment", "macro", "doc", "malicious file", "email attachment"]),
  T("T1190", "Exploit Public-Facing Application", "initial-access", ["exploit", "vulnerability", "cve", "web", "rce", "internet-facing", "upload", "webshell", "public"]),
  T("T1133", "External Remote Services", "initial-access", ["rdp", "vpn", "remote desktop", "remote service", "exposed", "citrix", "ssh"]),
  T("T1078", "Valid Accounts", "initial-access", ["valid account", "stolen credentials", "legitimate login", "compromised account"]),
  T("T1204", "User Execution", "execution", ["user opened", "double-click", "ran", "executed", "clicked"]),
  T("T1059", "Command and Scripting Interpreter", "execution", ["powershell", "cmd", "bash", "script", "command line", "wscript", "cscript"]),
  T("T1059.001", "PowerShell", "execution", ["powershell", "encoded command", "iex", "downloadstring"]),
  T("T1053", "Scheduled Task/Job", "persistence", ["scheduled task", "schtasks", "cron", "at job", "task scheduler"]),
  T("T1053.005", "Scheduled Task", "persistence", ["schtasks", "scheduled task", "onlogon", "task"]),
  T("T1547", "Boot or Logon Autostart Execution", "persistence", ["run key", "registry autostart", "startup folder", "logon"]),
  T("T1543", "Create or Modify System Process", "persistence", ["service", "new service", "daemon", "systemd", "sc create"]),
  T("T1136", "Create Account", "persistence", ["created account", "new user", "net user /add", "adduser"]),
  T("T1068", "Exploitation for Privilege Escalation", "privilege-escalation", ["privilege escalation", "local exploit", "kernel exploit", "getsystem"]),
  T("T1548", "Abuse Elevation Control Mechanism", "privilege-escalation", ["uac bypass", "sudo", "setuid", "elevation"]),
  T("T1055", "Process Injection", "defense-evasion", ["injection", "inject", "hollowing", "reflective", "dll injection"]),
  T("T1562", "Impair Defenses", "defense-evasion", ["disabled defender", "disable av", "stopped edr", "tamper", "disable logging", "cleared logs"]),
  T("T1562.001", "Disable or Modify Tools", "defense-evasion", ["disabled defender", "disable antivirus", "kill edr", "stop service"]),
  T("T1070", "Indicator Removal", "defense-evasion", ["cleared logs", "delete logs", "wevtutil", "timestomp", "wipe"]),
  T("T1027", "Obfuscated Files or Information", "defense-evasion", ["obfuscated", "encoded", "base64", "packed", "encrypted payload"]),
  T("T1003", "OS Credential Dumping", "credential-access", ["credential dump", "lsass", "mimikatz", "sam", "ntds", "hashdump"]),
  T("T1003.001", "LSASS Memory", "credential-access", ["lsass", "procdump", "comsvcs", "memory dump", "mimikatz"]),
  T("T1110", "Brute Force", "credential-access", ["brute force", "password spray", "guessing", "failed logons", "many attempts"]),
  T("T1552", "Unsecured Credentials", "credential-access", ["password in file", "plaintext credentials", "hardcoded", "config password"]),
  T("T1087", "Account Discovery", "discovery", ["net user", "account enumeration", "whoami", "list users", "net group"]),
  T("T1046", "Network Service Discovery", "discovery", ["port scan", "service scan", "network scan", "enumerate services"]),
  T("T1018", "Remote System Discovery", "discovery", ["ping sweep", "net view", "remote hosts", "arp", "discover hosts"]),
  T("T1021", "Remote Services", "lateral-movement", ["lateral movement", "rdp", "smb", "psexec", "winrm", "ssh", "wmi"]),
  T("T1021.002", "SMB/Windows Admin Shares", "lateral-movement", ["smb", "admin share", "psexec", "c$", "admin$", "lateral"]),
  T("T1021.001", "Remote Desktop Protocol", "lateral-movement", ["rdp", "remote desktop", "3389", "mstsc"]),
  T("T1570", "Lateral Tool Transfer", "lateral-movement", ["copied tool", "transferred binary", "staged tool", "pushed file"]),
  T("T1560", "Archive Collected Data", "collection", ["zip", "rar", "7z", "archived", "compressed data", "staging"]),
  T("T1071", "Application Layer Protocol", "command-and-control", ["c2", "http beacon", "dns tunneling", "https callback", "command and control"]),
  T("T1105", "Ingress Tool Transfer", "command-and-control", ["downloaded", "curl", "wget", "certutil", "bitsadmin", "payload download"]),
  T("T1567", "Exfiltration Over Web Service", "exfiltration", ["exfil", "upload to cloud", "mega", "dropbox", "data theft", "exfiltration"]),
  T("T1041", "Exfiltration Over C2 Channel", "exfiltration", ["exfil over c2", "data sent to c2", "beacon exfil"]),
  T("T1486", "Data Encrypted for Impact", "impact", ["ransomware", "encrypted files", "ransom note", "lockbit", "extension", "crypto-locker"]),
  T("T1490", "Inhibit System Recovery", "impact", ["deleted backups", "vssadmin delete", "shadow copies", "wbadmin", "disable recovery"]),
  T("T1489", "Service Stop", "impact", ["stopped service", "killed database", "service stop", "disrupt"]),
  T("T1498", "Network Denial of Service", "impact", ["ddos", "denial of service", "flood", "dos"]),

  // ---------- full ATT&CK Enterprise parent-technique coverage ----------
  // (sub-techniques inherit their parent's guidance in the response advisor)
  // Reconnaissance
  T("T1592", "Gather Victim Host Information", "reconnaissance", ["victim host info", "fingerprint", "recon host"]),
  T("T1589", "Gather Victim Identity Information", "reconnaissance", ["identity recon", "email harvest", "employee names"]),
  T("T1590", "Gather Victim Network Information", "reconnaissance", ["network recon", "dns recon", "whois", "ip ranges"]),
  T("T1591", "Gather Victim Org Information", "reconnaissance", ["org recon", "business relationships", "org chart"]),
  T("T1598", "Phishing for Information", "reconnaissance", ["phishing recon", "pretexting", "credential phish recon"]),
  T("T1597", "Search Closed Sources", "reconnaissance", ["closed sources", "threat intel purchase", "dark web"]),
  T("T1596", "Search Open Technical Databases", "reconnaissance", ["shodan", "censys", "certificate transparency"]),
  T("T1593", "Search Open Websites/Domains", "reconnaissance", ["social media recon", "search engines", "osint"]),
  T("T1594", "Search Victim-Owned Websites", "reconnaissance", ["website recon", "site crawl"]),
  // Resource Development
  T("T1583", "Acquire Infrastructure", "resource-development", ["acquire infrastructure", "register domain", "vps", "attacker infra"]),
  T("T1586", "Compromise Accounts", "resource-development", ["compromise accounts", "stolen social media account"]),
  T("T1584", "Compromise Infrastructure", "resource-development", ["compromise infrastructure", "hijacked server", "botnet"]),
  T("T1587", "Develop Capabilities", "resource-development", ["develop malware", "build tooling", "code signing cert"]),
  T("T1585", "Establish Accounts", "resource-development", ["establish accounts", "fake persona", "burner email"]),
  T("T1588", "Obtain Capabilities", "resource-development", ["obtain tools", "buy exploit", "malware purchase"]),
  T("T1608", "Stage Capabilities", "resource-development", ["stage payload", "upload malware", "host tool"]),
  // Initial Access
  T("T1189", "Drive-by Compromise", "initial-access", ["drive-by", "watering hole", "malicious website"]),
  T("T1200", "Hardware Additions", "initial-access", ["hardware implant", "rogue usb", "malicious device"]),
  T("T1091", "Replication Through Removable Media", "initial-access", ["usb worm", "removable media", "autorun"]),
  T("T1195", "Supply Chain Compromise", "initial-access", ["supply chain", "tainted update", "third-party compromise"]),
  T("T1199", "Trusted Relationship", "initial-access", ["trusted relationship", "third party access", "msp compromise"]),
  // Execution
  T("T1651", "Cloud Administration Command", "execution", ["cloud admin command", "run command", "ssm runcommand"]),
  T("T1609", "Container Administration Command", "execution", ["container admin", "kubectl exec", "docker exec"]),
  T("T1610", "Deploy Container", "execution", ["deploy container", "malicious container", "rogue pod"]),
  T("T1203", "Exploitation for Client Execution", "execution", ["client exploit", "document exploit", "browser exploit"]),
  T("T1559", "Inter-Process Communication", "execution", ["ipc", "com object", "dde"]),
  T("T1106", "Native API", "execution", ["native api", "createprocess", "syscall"]),
  T("T1648", "Serverless Execution", "execution", ["serverless", "lambda", "cloud function"]),
  T("T1129", "Shared Modules", "execution", ["shared modules", "dll load", "loadlibrary"]),
  T("T1072", "Software Deployment Tools", "execution", ["deployment tools", "sccm", "rmm push"]),
  T("T1569", "System Services", "execution", ["system services", "service execution", "sc start"]),
  T("T1047", "Windows Management Instrumentation", "execution", ["wmi", "wmic", "win32_process"]),
  // Persistence
  T("T1098", "Account Manipulation", "persistence", ["account manipulation", "add to group", "ssh key added", "mailbox rule"]),
  T("T1197", "BITS Jobs", "persistence", ["bits job", "bitsadmin", "background transfer"]),
  T("T1037", "Boot or Logon Initialization Scripts", "persistence", ["logon script", "init script", "rc.local"]),
  T("T1176", "Browser Extensions", "persistence", ["browser extension", "malicious addon", "chrome extension"]),
  T("T1554", "Compromise Client Software Binary", "persistence", ["trojanized binary", "backdoored app", "patched binary"]),
  T("T1546", "Event Triggered Execution", "persistence", ["event triggered", "wmi subscription", "accessibility feature"]),
  T("T1574", "Hijack Execution Flow", "persistence", ["dll hijack", "search order hijack", "path interception"]),
  T("T1525", "Implant Internal Image", "persistence", ["implant image", "backdoored container image", "malicious ami"]),
  T("T1556", "Modify Authentication Process", "persistence", ["modify authentication", "skeleton key", "custom ssp", "pam"]),
  T("T1137", "Office Application Startup", "persistence", ["office startup", "outlook rules", "office template", "vsto"]),
  T("T1542", "Pre-OS Boot", "persistence", ["bootkit", "bios", "uefi", "mbr"]),
  T("T1505", "Server Software Component", "persistence", ["web shell", "iis module", "sql stored procedure", "transport agent"]),
  T("T1205", "Traffic Signaling", "persistence", ["port knocking", "traffic signaling", "magic packet"]),
  // Privilege Escalation
  T("T1134", "Access Token Manipulation", "privilege-escalation", ["token manipulation", "token impersonation", "runas"]),
  T("T1484", "Domain or Tenant Policy Modification", "privilege-escalation", ["gpo abuse", "group policy modification", "domain policy"]),
  T("T1611", "Escape to Host", "privilege-escalation", ["container escape", "escape to host", "privileged container"]),
  // Defense Evasion
  T("T1622", "Debugger Evasion", "defense-evasion", ["debugger evasion", "anti-debug", "isdebuggerpresent"]),
  T("T1140", "Deobfuscate/Decode Files or Information", "defense-evasion", ["deobfuscate", "decode", "certutil decode"]),
  T("T1006", "Direct Volume Access", "defense-evasion", ["direct volume access", "raw disk read", "ntfs parse"]),
  T("T1480", "Execution Guardrails", "defense-evasion", ["guardrails", "environmental keying", "targeted execution"]),
  T("T1211", "Exploitation for Defense Evasion", "defense-evasion", ["exploit for evasion", "bypass security product"]),
  T("T1222", "File and Directory Permissions Modification", "defense-evasion", ["permissions modification", "icacls", "chmod", "takeown"]),
  T("T1564", "Hide Artifacts", "defense-evasion", ["hidden files", "hidden window", "alternate data stream", "ads"]),
  T("T1202", "Indirect Command Execution", "defense-evasion", ["indirect execution", "forfiles", "pcalua"]),
  T("T1036", "Masquerading", "defense-evasion", ["masquerading", "renamed binary", "spoofed name", "svchost impersonation"]),
  T("T1578", "Modify Cloud Compute Infrastructure", "defense-evasion", ["modify cloud compute", "create snapshot", "revert vm"]),
  T("T1112", "Modify Registry", "defense-evasion", ["modify registry", "reg add", "reg delete"]),
  T("T1601", "Modify System Image", "defense-evasion", ["modify system image", "patch os image", "firmware modify"]),
  T("T1599", "Network Boundary Bridging", "defense-evasion", ["network boundary bridging", "nat traversal"]),
  T("T1647", "Plist File Modification", "defense-evasion", ["plist modification", "macos plist"]),
  T("T1620", "Reflective Code Loading", "defense-evasion", ["reflective loading", "reflective dll", "in-memory load"]),
  T("T1207", "Rogue Domain Controller", "defense-evasion", ["rogue dc", "dcshadow"]),
  T("T1014", "Rootkit", "defense-evasion", ["rootkit", "kernel driver", "hooking"]),
  T("T1218", "System Binary Proxy Execution", "defense-evasion", ["lolbin", "rundll32", "regsvr32", "mshta"]),
  T("T1216", "System Script Proxy Execution", "defense-evasion", ["script proxy", "pubprn", "syncappvpublishingserver"]),
  T("T1221", "Template Injection", "defense-evasion", ["template injection", "remote template", "docx template"]),
  T("T1127", "Trusted Developer Utilities Proxy Execution", "defense-evasion", ["msbuild", "trusted dev utilities", "devtoolslauncher"]),
  T("T1535", "Unused/Unsupported Cloud Regions", "defense-evasion", ["unused cloud region", "cloud region abuse"]),
  T("T1550", "Use Alternate Authentication Material", "defense-evasion", ["pass the hash", "pass the ticket", "pth", "ptt", "overpass the hash"]),
  T("T1497", "Virtualization/Sandbox Evasion", "defense-evasion", ["sandbox evasion", "vm detection", "anti-sandbox"]),
  T("T1600", "Weaken Encryption", "defense-evasion", ["weaken encryption", "disable crypto", "downgrade tls"]),
  T("T1220", "XSL Script Processing", "defense-evasion", ["xsl", "wmic xsl", "msxsl"]),
  // Credential Access
  T("T1557", "Adversary-in-the-Middle", "credential-access", ["mitm", "adversary in the middle", "llmnr", "ntlm relay", "arp spoof"]),
  T("T1555", "Credentials from Password Stores", "credential-access", ["password store", "browser passwords", "keychain", "credential manager"]),
  T("T1212", "Exploitation for Credential Access", "credential-access", ["exploit for creds", "credential exploit"]),
  T("T1187", "Forced Authentication", "credential-access", ["forced authentication", "unc path", "responder", "hash leak"]),
  T("T1606", "Forge Web Credentials", "credential-access", ["forge web credentials", "saml forgery", "golden saml", "cookie forge"]),
  T("T1056", "Input Capture", "credential-access", ["keylogger", "input capture", "credential prompt"]),
  T("T1111", "Multi-Factor Authentication Interception", "credential-access", ["mfa interception", "otp theft", "sms intercept"]),
  T("T1621", "Multi-Factor Authentication Request Generation", "credential-access", ["mfa fatigue", "push bombing", "mfa spam"]),
  T("T1040", "Network Sniffing", "credential-access", ["network sniffing", "packet capture", "tcpdump", "wireshark"]),
  T("T1528", "Steal Application Access Token", "credential-access", ["steal oauth token", "access token theft", "app token"]),
  T("T1558", "Steal or Forge Kerberos Tickets", "credential-access", ["kerberoasting", "golden ticket", "silver ticket", "kerberos", "asreproast"]),
  T("T1539", "Steal Web Session Cookie", "credential-access", ["session cookie theft", "cookie stealing", "session hijack"]),
  // Discovery
  T("T1010", "Application Window Discovery", "discovery", ["window discovery", "foreground window"]),
  T("T1217", "Browser Information Discovery", "discovery", ["browser bookmarks", "browser history discovery"]),
  T("T1580", "Cloud Infrastructure Discovery", "discovery", ["cloud infrastructure discovery", "describe instances"]),
  T("T1538", "Cloud Service Dashboard", "discovery", ["cloud dashboard", "console browsing"]),
  T("T1526", "Cloud Service Discovery", "discovery", ["cloud service discovery", "enumerate services"]),
  T("T1619", "Cloud Storage Object Discovery", "discovery", ["s3 enumeration", "bucket discovery", "list objects"]),
  T("T1613", "Container and Resource Discovery", "discovery", ["container discovery", "kubectl get", "docker ps"]),
  T("T1652", "Device Driver Discovery", "discovery", ["driver discovery", "driverquery"]),
  T("T1482", "Domain Trust Discovery", "discovery", ["domain trust", "nltest", "trust enumeration"]),
  T("T1083", "File and Directory Discovery", "discovery", ["file discovery", "dir listing", "find files"]),
  T("T1615", "Group Policy Discovery", "discovery", ["group policy discovery", "gpresult", "gpo enum"]),
  T("T1135", "Network Share Discovery", "discovery", ["share discovery", "net view", "smb shares"]),
  T("T1201", "Password Policy Discovery", "discovery", ["password policy", "net accounts"]),
  T("T1120", "Peripheral Device Discovery", "discovery", ["peripheral discovery", "usb enumeration"]),
  T("T1069", "Permission Groups Discovery", "discovery", ["group discovery", "net group", "whoami groups"]),
  T("T1057", "Process Discovery", "discovery", ["process discovery", "tasklist", "ps aux"]),
  T("T1012", "Query Registry", "discovery", ["query registry", "reg query"]),
  T("T1518", "Software Discovery", "discovery", ["software discovery", "installed programs", "security software discovery"]),
  T("T1082", "System Information Discovery", "discovery", ["system info", "systeminfo", "uname"]),
  T("T1614", "System Location Discovery", "discovery", ["system location", "geolocation", "language discovery"]),
  T("T1016", "System Network Configuration Discovery", "discovery", ["ipconfig", "ifconfig", "network config discovery"]),
  T("T1049", "System Network Connections Discovery", "discovery", ["netstat", "network connections", "established sessions"]),
  T("T1033", "System Owner/User Discovery", "discovery", ["whoami", "user discovery", "logged on users"]),
  T("T1007", "System Service Discovery", "discovery", ["service discovery", "sc query", "net start"]),
  T("T1124", "System Time Discovery", "discovery", ["system time", "net time", "time discovery"]),
  // Lateral Movement
  T("T1210", "Exploitation of Remote Services", "lateral-movement", ["exploit remote service", "smb exploit", "eternalblue", "smbghost"]),
  T("T1534", "Internal Spearphishing", "lateral-movement", ["internal spearphishing", "internal phish"]),
  T("T1563", "Remote Service Session Hijacking", "lateral-movement", ["session hijack", "rdp hijack", "ssh hijack"]),
  T("T1080", "Taint Shared Content", "lateral-movement", ["taint shared content", "poisoned share", "scf file"]),
  // Collection
  T("T1123", "Audio Capture", "collection", ["audio capture", "microphone"]),
  T("T1119", "Automated Collection", "collection", ["automated collection", "scripted collection"]),
  T("T1185", "Browser Session Hijacking", "collection", ["browser session hijack", "man in the browser"]),
  T("T1115", "Clipboard Data", "collection", ["clipboard", "clipboard capture"]),
  T("T1530", "Data from Cloud Storage", "collection", ["cloud storage data", "s3 download", "bucket exfil"]),
  T("T1602", "Data from Configuration Repository", "collection", ["config repository", "snmp", "network device config"]),
  T("T1213", "Data from Information Repositories", "collection", ["sharepoint", "confluence", "wiki", "information repository"]),
  T("T1005", "Data from Local System", "collection", ["local system data", "file collection"]),
  T("T1039", "Data from Network Shared Drive", "collection", ["network share data", "file server collection"]),
  T("T1025", "Data from Removable Media", "collection", ["removable media data", "usb collection"]),
  T("T1074", "Data Staged", "collection", ["data staged", "staging directory", "archive staging"]),
  T("T1114", "Email Collection", "collection", ["email collection", "mailbox export", "pst export", "mail forwarding"]),
  T("T1113", "Screen Capture", "collection", ["screen capture", "screenshot"]),
  T("T1125", "Video Capture", "collection", ["video capture", "webcam"]),
  // Command and Control
  T("T1092", "Communication Through Removable Media", "command-and-control", ["removable media c2", "air-gap c2"]),
  T("T1659", "Content Injection", "command-and-control", ["content injection", "traffic injection"]),
  T("T1132", "Data Encoding", "command-and-control", ["data encoding", "base64 c2"]),
  T("T1001", "Data Obfuscation", "command-and-control", ["data obfuscation", "c2 obfuscation", "steganography"]),
  T("T1568", "Dynamic Resolution", "command-and-control", ["dga", "domain generation", "fast flux", "dynamic dns"]),
  T("T1573", "Encrypted Channel", "command-and-control", ["encrypted channel", "tls c2", "custom crypto c2"]),
  T("T1008", "Fallback Channels", "command-and-control", ["fallback channel", "backup c2"]),
  T("T1104", "Multi-Stage Channels", "command-and-control", ["multi-stage c2", "staged channel"]),
  T("T1095", "Non-Application Layer Protocol", "command-and-control", ["icmp c2", "non-application protocol", "raw socket"]),
  T("T1571", "Non-Standard Port", "command-and-control", ["non-standard port", "odd port c2"]),
  T("T1572", "Protocol Tunneling", "command-and-control", ["protocol tunneling", "dns tunneling", "ssh tunnel"]),
  T("T1090", "Proxy", "command-and-control", ["proxy", "socks", "relay", "tor"]),
  T("T1219", "Remote Access Software", "command-and-control", ["remote access software", "anydesk", "teamviewer", "rmm tool"]),
  T("T1102", "Web Service", "command-and-control", ["web service c2", "github c2", "pastebin", "dead drop"]),
  // Exfiltration
  T("T1020", "Automated Exfiltration", "exfiltration", ["automated exfiltration", "scripted exfil"]),
  T("T1030", "Data Transfer Size Limits", "exfiltration", ["transfer size limits", "chunked exfil"]),
  T("T1048", "Exfiltration Over Alternative Protocol", "exfiltration", ["exfil alternative protocol", "dns exfil", "ftp exfil", "icmp exfil"]),
  T("T1011", "Exfiltration Over Other Network Medium", "exfiltration", ["exfil other medium", "bluetooth exfil", "wifi exfil"]),
  T("T1052", "Exfiltration Over Physical Medium", "exfiltration", ["physical exfil", "usb exfil"]),
  T("T1029", "Scheduled Transfer", "exfiltration", ["scheduled transfer", "timed exfil"]),
  T("T1537", "Transfer Data to Cloud Account", "exfiltration", ["cloud account exfil", "s3 copy", "attacker bucket"]),
  // Impact
  T("T1531", "Account Access Removal", "impact", ["account access removal", "locked out", "password changed by attacker"]),
  T("T1485", "Data Destruction", "impact", ["data destruction", "file deletion", "sdelete", "wiped files"]),
  T("T1565", "Data Manipulation", "impact", ["data manipulation", "tampering", "altered records"]),
  T("T1491", "Defacement", "impact", ["defacement", "website defacement", "message left"]),
  T("T1561", "Disk Wipe", "impact", ["disk wipe", "mbr wipe", "wiper malware"]),
  T("T1499", "Endpoint Denial of Service", "impact", ["endpoint dos", "resource exhaustion", "service crash"]),
  T("T1495", "Firmware Corruption", "impact", ["firmware corruption", "bricked device", "bios wipe"]),
  T("T1496", "Resource Hijacking", "impact", ["cryptomining", "resource hijacking", "cryptojacking"]),
  T("T1529", "System Shutdown/Reboot", "impact", ["shutdown", "reboot", "forced restart"]),
];

function suggest(text) {
  const t = String(text || "").toLowerCase();
  if (!t.trim()) return [];
  const scored = techniques.map((x) => {
    let s = 0;
    for (const k of x.keywords) if (t.includes(k)) s += k.length > 6 ? 3 : 2;
    if (t.includes(x.name.toLowerCase())) s += 4;
    return { ...x, score: s };
  }).filter((x) => x.score > 0).sort((a, b) => b.score - a.score);
  return scored.slice(0, 6);
}
module.exports = { tactics, techniques, suggest };
